#!/usr/bin/env bash
#
# install.sh — install Withy on macOS.
#
# Safe to re-run: every step checks before it acts, and an existing Hammerspoon
# configuration is appended to, never replaced.
#
#   ./install.sh                 install dictation (no on-device model)
#   ./install.sh --with-llm      also install Ollama for on-device polishing
#   ./install.sh --model base.en use a smaller, faster Whisper model
#   ./install.sh --polish-command "claude -p"
#                                configure polishing to use a local CLI agent
#   ./install.sh --polish-backend off|local|command|openai|anthropic
#
set -euo pipefail

MODEL_NAME="large-v3-turbo"
# An assistant running this installer can work out which command-line agents
# exist on THIS machine and what the user prefers, then pass the answer in — so
# the user never has to discover or type it. See LLM.md.
POLISH_COMMAND=""
POLISH_BACKEND=""
# On-device polishing is OPTIONAL and adds a ~2GB download plus a background
# runner. It can be added or removed later from the menu, so the installer does
# not assume it — see --with-llm.
WITH_LLM=0
LLM_MODEL="qwen2.5:3b"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-llm) WITH_LLM=0; shift ;;
    --with-llm) WITH_LLM=1; shift ;;
    --polish-command) POLISH_COMMAND="$2"; shift 2 ;;
    --polish-backend) POLISH_BACKEND="$2"; shift 2 ;;
    --model)  MODEL_NAME="$2"; shift 2 ;;
    --llm-model) LLM_MODEL="$2"; shift 2 ;;
    -h|--help) sed -n '3,12p' "$0"; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP="$HOME/.local/share/withy/app"
BIN="$HOME/.local/bin/withy"
CONF="$HOME/.config/withy"
SPOONS="$HOME/.hammerspoon/Spoons"
INIT="$HOME/.hammerspoon/init.lua"
LOADLINE='hs.loadSpoon("Withy"):start()'

say()  { printf '\033[1m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[33m  ! %s\033[0m\n' "$*"; }

[[ "$(uname -s)" == "Darwin" ]] || { echo "Withy is macOS-only." >&2; exit 1; }

# ── dependencies ─────────────────────────────────────────────────────────
if ! command -v brew >/dev/null 2>&1; then
  echo "Homebrew is required: https://brew.sh" >&2
  exit 1
fi

say "Installing dependencies"
for pkg in whisper-cpp ffmpeg; do
  if brew list --formula "$pkg" >/dev/null 2>&1; then
    echo "  $pkg already installed"
  else
    brew install "$pkg"
  fi
done

if ! command -v hs >/dev/null 2>&1 && [[ ! -d /Applications/Hammerspoon.app ]]; then
  brew install --cask hammerspoon
else
  echo "  hammerspoon already installed"
fi

if [[ "$WITH_LLM" == "1" ]]; then
  command -v ollama >/dev/null 2>&1 || brew install ollama
  # `ollama pull` needs the daemon; `ollama serve` is a no-op if it is running.
  pgrep -qx ollama || (nohup ollama serve >/dev/null 2>&1 & sleep 2)
  if ollama list 2>/dev/null | awk 'NR>1 {print $1}' | grep -qx "$LLM_MODEL"; then
    echo "  $LLM_MODEL already pulled"
  else
    say "Pulling $LLM_MODEL (about 2 GB, one time)"
    ollama pull "$LLM_MODEL"
  fi
fi

# ── whisper model ────────────────────────────────────────────────────────
MODEL_DIR="$(brew --prefix)/share/whisper-cpp"
MODEL_PATH="$MODEL_DIR/ggml-$MODEL_NAME.bin"
if [[ -f "$MODEL_PATH" ]]; then
  echo "  speech model already present"
else
  say "Downloading the speech model ($MODEL_NAME)"
  mkdir -p "$MODEL_DIR"
  curl -fL --progress-bar \
    "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-$MODEL_NAME.bin" \
    -o "$MODEL_PATH.part"
  mv "$MODEL_PATH.part" "$MODEL_PATH"
fi

# ── application ──────────────────────────────────────────────────────────
say "Installing Withy"
mkdir -p "$APP" "$(dirname "$BIN")" "$CONF" "$SPOONS"
rm -rf "${APP:?}/withy"
cp -R "$SRC/withy" "$APP/withy"

# The launcher hard-codes its interpreter and PYTHONPATH: Hammerspoon spawns it
# with a minimal environment, so nothing here may depend on the user's PATH.
cat > "$BIN" <<EOF
#!/bin/sh
# Generated by install.sh — do not edit; re-run the installer instead.
# Hammerspoon spawns this with almost no environment; give it a usable PATH
# so the tools resolve the same way they do in a terminal.
export PATH="$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PYTHONPATH="$APP"
exec /usr/bin/python3 -m withy "\$@"
EOF
chmod +x "$BIN"

rm -rf "$SPOONS/Withy.spoon"
cp -R "$SRC/Withy.spoon" "$SPOONS/Withy.spoon"

# ── configuration ────────────────────────────────────────────────────────
"$BIN" settings "cli_path=$BIN" "whisper_model=$MODEL_PATH" \
                "llm_model=$LLM_MODEL" "postprocess=$WITH_LLM" >/dev/null
"$BIN" vocab path >/dev/null    # creates the vocabulary file on first run

# Polishing choice, if one was passed in.
if [[ -n "$POLISH_COMMAND" ]]; then
  say "Configuring polishing to use: $POLISH_COMMAND"
  "$BIN" set-command "$POLISH_COMMAND" || true
  "$BIN" settings polish_backend=command postprocess=true >/dev/null
  # Verify rather than assume: a wrong command fails silently and safely, and
  # the user would never learn why polishing does nothing.
  if ! "$BIN" test-command; then
    warn "that command did not pass its check — polishing will do nothing until it is fixed"
  fi
elif [[ -n "$POLISH_BACKEND" ]]; then
  if [[ "$POLISH_BACKEND" == "off" ]]; then
    "$BIN" settings postprocess=false >/dev/null
  else
    "$BIN" settings "polish_backend=$POLISH_BACKEND" postprocess=true >/dev/null
  fi
  say "Polishing backend: $POLISH_BACKEND"
fi

# ── hammerspoon wiring ───────────────────────────────────────────────────
# Append, never overwrite: the user may already run other Hammerspoon tools,
# and clobbering their config is unforgivable for an installer.
if [[ -f "$INIT" ]] && grep -qF 'loadSpoon("Withy")' "$INIT"; then
  echo "  hammerspoon already configured"
else
  say "Adding Withy to your Hammerspoon config"
  [[ -f "$INIT" ]] && cp "$INIT" "$INIT.withy-backup.$(date +%s)"
  printf '\n-- Withy (local dictation)\n%s\n' "$LOADLINE" >> "$INIT"
fi

open -a Hammerspoon 2>/dev/null || true
sleep 1
# Reload WITHOUT waiting. `hs -c 'hs.reload()'` never returns: the reload tears
# down the very IPC channel the CLI is blocked on reading, so the client hangs
# forever. Detach it and move on.
if command -v hs >/dev/null 2>&1; then
  ( hs -c 'hs.reload()' >/dev/null 2>&1 & ) || true
  sleep 2
fi

# ── verify ───────────────────────────────────────────────────────────────
say "Checking the install"
"$BIN" diagnose || warn "some checks failed — see above"

cat <<'EOF'

  Withy is installed.

  ONE THING LEFT, and it cannot be scripted: macOS permissions.
  Open System Settings > Privacy & Security and grant Hammerspoon:
      Accessibility      (so it can type into other apps)
      Input Monitoring   (so it can see the record key)
      Microphone         (prompted the first time you dictate)

  Then hold RIGHT OPTION, say something, and let go.

  The 🎙 in your menu bar holds everything else: your recent dictations,
  the record key, and your vocabulary file.

  If the record key collides with something, change it there — fn is the
  most comfortable key, but Apple Dictation and most commercial dictation
  tools already use it.
EOF
